function [timeConstant] = lockin_SetTimeConstant(app,freq)
    % period = 1/(2*pi*freq);
    tc = 1/(freq*10^(-3/10)); % The tc is set to the inverse of -3 dB the freq
    lockinTC = 0;
    timeConstant = 10E-6;
    if (tc <= 10E-6)
        lockinTC = 0;
        timeConstant = 10E-6;
    elseif (10e-6 < tc && tc <= 30E-6)
        lockinTC = 1;
        timeConstant = 30E-6;
    elseif (30E-6 < tc && tc <= 100E-6)
        lockinTC = 2;
        timeConstant = 100E-6;
    elseif (100E-6 < tc && tc <= 300E-6)
        lockinTC = 3;
        timeConstant = 300E-6;
    elseif (300E-6 < tc && tc <= 1E-3)
        lockinTC = 4;
        timeConstant = 1E-3;
    elseif (1E-3 < tc && tc <= 3E-3)
        lockinTC = 5;
        timeConstant = 3E-3;
    elseif (3E-3 < tc && tc <= 10E-3)
        lockinTC = 6;
        timeConstant = 10E-3;
    elseif (10E-3 < tc && tc <= 30E-3)
        lockinTC = 7;
        timeConstant = 30E-3;
    elseif (30E-3 < tc && tc <= 100E-3)
        lockinTC = 8;
        timeConstant = 100E-3;
    elseif (100E-3 < tc && tc <= 300E-3)
        lockinTC = 9;
        timeConstant = 300E-3;
    elseif (300E-3 < tc && tc <= 1)
        lockinTC = 10;
        timeConstant = 1;
    elseif (1 < tc && tc <= 3)
        lockinTC = 11;
        timeConstant = 3;
    elseif (3 < tc && tc <= 10)
        lockinTC = 12;
        timeConstant = 10;
    elseif (10 < tc && tc <= 30)
        lockinTC = 13;
        timeConstant = 30;
    elseif (30 < tc && tc <= 100)
        lockinTC = 14;
        timeConstant = 100;
    elseif (100 < tc && tc <= 300)
        lockinTC = 15;
        timeConstant = 300
    elseif (300 < tc && tc <= 1E3)
        lockinTC = 16;
        timeConstant = 1E3;
    elseif (1E3 < tc && tc <= 3E3)
        lockinTC = 17;
        timeConstant = 3E3;
    elseif (3E3 < tc && tc <= 10E3)
        lockinTC = 18;
        timeConstant = 10E3;
    elseif (10E3 < tc && tc <= 30E3)
        lockinTC = 19;
        timeConstant = 30E3;
    end

    fprintf(app.handle_lockin,'OFLT %d', lockinTC); % sets the time constat